		<tr class="globalparam">
			<td style="width:35%;">
				<label for="accesskey"> Accesskey </label>
			</td>
			<td>
				<input style="width:98%;" type="text" id="accesskey" name="accesskey" maxlength="50" class="ui-widget-content ui-corner-all input-ui" />
			</td>
			<td class="help" title="<?php echo $accesskey?>"><span class='ui-icon ui-icon-info'></span></td>
		</tr>
		<tr class="globalparam">
			<td>
				<label for="class"> Class </label>
			</td>
			<td>
				<input  style="width:98%;" type="text" id="class" name="class" maxlength="300" class="ui-widget-content ui-corner-all input-ui"/>
			</td>
			<td class="help" title="<?php echo $class?>"><span class='ui-icon ui-icon-info'></span></td>
		</tr>
		<tr class="globalparam">
			<td>
				<label for="contenteditable"> Content editable </label>
			</td>
			<td>
				<select id="contenteditable" name="contenteditable" class="ui-widget-content ui-corner-all select-ui"><option value="">Select</option><option value="true">True</option><option value="false">False</option><option value="inherit">Inherit</option></select>
			</td>
			<td class="help" title="<?php echo $contenteditable?>"><span class='ui-icon ui-icon-info'></span></td>
		</tr>
		<tr class="globalparam">
			<td>
				<label for="contextmenu"> Context menu </label>
			</td>
			<td>
				<input style="width:98%;" type="text" id="contextmenu" name="contextmenu" size="10" maxlength="50" class="ui-widget-content ui-corner-all input-ui"/>
			</td>
			<td class="help" title="<?php echo $contextmenu?>"><span class='ui-icon ui-icon-info'></span></td>
		</tr>
		<tr class="globalparam">
			<td>
				<label for="dir"> Direction </label>
			</td>
			<td>
				<select id="dir" name="dir" class="ui-widget-content ui-corner-all select-ui"><option value="">Select</option><option value="ltr">ltr</option><option value="rtl">rtl</option><option value="auto">auto</option></select>
			</td>
			<td class="help" title="<?php echo $dir?>"><span class='ui-icon ui-icon-info'></span></td>
		</tr>
		<tr class="globalparam">
			<td>
				<label for="draggable"> Draggable </label>
			</td>
			<td>
				<select id="draggable" name="draggable" class="ui-widget-content ui-corner-all select-ui"><option value="">Select</option><option value="auto">Auto</option><option value="true">Yes</option><option value="false">No</option></select>
			</td>
			<td class="help" title="<?php echo $draggable?>"><span class='ui-icon ui-icon-info'></span></td>
		</tr>
		<tr class="globalparam">
			<td>
				<label for="dropzone"> Drop zone </label>
			</td>
			<td>
				<select id="dropzone" name="dropzone" class="ui-widget-content ui-corner-all select-ui"><option value="">Select</option><option value="copy">Copy</option><option value="move">Move</option><option value="link">Link</option></select>
			</td>
			<td class="help" title="<?php echo $dropzone?>"><span class='ui-icon ui-icon-info'></span></td>
		</tr>
		<tr class="globalparam">
			<td>
				<label for="hidden"> Hidden </label>
			</td>
			<td>
				<input type="checkbox" id="hidden" name="hidden" class="ui-widget-content ui-corner-all input-ui"/>
			</td>
			<td class="help" title="<?php echo $hidden?>"><span class='ui-icon ui-icon-info'></span></td>
		</tr>
		<tr class="globalparam">
			<td>
				<label for="id"> Id </label>
			</td>
			<td>
				<input style="width:98%;" type="text" id="id" name="id"  maxlength="50" class="ui-widget-content ui-corner-all input-ui"/>
			</td>
			<td class="help" title="<?php echo $id?>"><span class='ui-icon ui-icon-info'></span></td>
		</tr>
		<tr class="globalparam">
			<td>
				<label for="lang"> Language code </label>
			</td>
			<td>
				<input style="width:98%;" type="text" id="lang" name="lang"  maxlength="50" class="ui-widget-content ui-corner-all input-ui"/>
			</td>
			<td class="help" title="<?php echo $lang?>"><span class='ui-icon ui-icon-info'></span></td>			
		</tr>
		<tr class="globalparam">
			<td>
				<label for="spellcheck"> Spelling and grammar</label>
			</td>
			<td>
				<select id="spellcheck" name="spellcheck" class="ui-widget-content ui-corner-all select-ui"><option value="">Select</option><option value="true">Yes</option><option value="false">No</option></select>
			</td>
			<td class="help" title="<?php echo $spellcheck?>"><span class='ui-icon ui-icon-info'></span></td>
		</tr>
		<tr class="globalparam">
			<td>
				<label for="style"> Style </label>
			</td>
			<td>
				<input style="width:98%;" type="text" id="style" name="style"  maxlength="300" class="ui-widget-content ui-corner-all input-ui"/>
			</td>
			<td class="help" title="<?php echo $style?>"><span class='ui-icon ui-icon-info'></span></td>
		</tr>
		<tr class="globalparam">
			<td>
				<label for="tabindex"> Tabindex </label>
			</td>
			<td>
				<input style="width:98%;" type="text" id="tabindex" name="tabindex" maxlength="300" class="ui-widget-content ui-corner-all input-ui"/>
			</td>
			<td class="help" title="<?php echo $tabindex?>"><span class='ui-icon ui-icon-info'></span></td>
		</tr>
		<tr class="globalparam">
			<td>
				<label for="title"> Title </label>
			</td>
			<td>
				<input style="width:98%;" type="text" id="title" name="title" maxlength="300" class="ui-widget-content ui-corner-all input-ui"/>
			</td>
			<td class="help" title="<?php echo $title?>"><span class='ui-icon ui-icon-info'></span></td>
		</tr>
